[package]
name = "the_blue_alliance"
version = "0.1.0"
authors = ["Conner Ebbinghaus <connerebbinghaus@gmail.com>"]

[dependencies]
hyper = "0.12"
hyper-tls = "0.2"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
tokio-core = "0.1"